[deploy]
preDeployCommand = "npx prisma db push --accept-data-loss && npx prisma db seed"
startCommand = "node_modules/.bin/next start -p ${PORT:-3000}"
healthcheckPath = "/"
healthcheckTimeout = 120
